name: foo compile

on: workflow_dispatch


jobs:
  Win:
    runs-on: windows-latest
    name: MSVC-${{matrix.cxx}}
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          python -m pip install meson ninja

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Compile
        env:
          CC: cl
          CXX: cl
        run: |
          meson build --buildtype=release # Default is debug
          cd build
          ninja
      - run: ls -alR
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: win32
          path: |
            build/spng*
            build/subprojects/zlib*/z.dll
